version: "3.8"

services:

  spring-restful-api-kotlin:
    container_name: spring-restful-api-kotlin
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-restful-api-kotlin:0.0.1
    ports:
      - "8080:8080"
    environment:
      DATABASE_USERNAME: kotlin
      DATABASE_PASSWORD: kotlin
      DATABASE_URL: jdbc:mysql://spring-restful-api-kotlin-mysql:3306/belajar_spring_restful_api_kotlin
      APP_PORT: 8080
    depends_on:
      - spring-restful-api-kotlin-mysql

  spring-restful-api-kotlin-mysql:
    container_name: spring-restful-api-kotlin-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belajar_spring_restful_api_kotlin
      MYSQL_USER: kotlin
      MYSQL_PASSWORD: kotlin
    volumes:
      - "./backup:/data/backup"
