spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:kotlin}
    password: ${DATABASE_PASSWORD:kotlin}
    url: jdbc:mysql://localhost:3306/belajar_spring_restful_api_kotlin
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true